name: Python CI workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "{{python_version}}"
      - run: pip install -r requirements.txt
        working-directory: "./{{working_directory}}"
      - run: pytest
        working-directory: "./{{working_directory}}"
